version: '3'

services:
  redis-cluster-1:
    image: redis
    restart: always
    container_name: redis-cluster-1
    ports:
      - 7000:6379
      - 17000:16379
    volumes:
      - ./data/7000:/data
    environment:
      - CLUSTER_ANNOUNCE_PORT=7000
      - CLUSTER_ANNOUNCE_BUS_PORT=17000
    command: [
      '--appendonly ${REDIS_APPENDONLY}',
      '--cluster-enabled ${REDIS_CLUSTER_ENABLED}',
      '--cluster-config-file ${REDIS_CLUSTER_CONFIG_FILE}',
      '--cluster-node-timeout ${REDIS_CLUSTER_NODE_TIMEOUT}',
      '--cluster-announce-ip ${HOST_IP}',
      '--cluster-announce-port ${CLUSTER_ANNOUNCE_PORT}',
      '--cluster-announce-bus-port ${CLUSTER_ANNOUNCE_BUS_PORT}'
    ]

  redis-cluster-2:
    image: redis
    restart: always
    container_name: redis-cluster-2
    ports:
      - 7001:6379
      - 17001:16379
    volumes:
      - ./data/7001:/data
    environment:
      - CLUSTER_ANNOUNCE_PORT=7001
      - CLUSTER_ANNOUNCE_BUS_PORT=17001
    command: [
      '--appendonly ${REDIS_APPENDONLY}',
      '--cluster-enabled ${REDIS_CLUSTER_ENABLED}',
      '--cluster-config-file ${REDIS_CLUSTER_CONFIG_FILE}',
      '--cluster-node-timeout ${REDIS_CLUSTER_NODE_TIMEOUT}',
      '--cluster-announce-ip ${HOST_IP}',
      '--cluster-announce-port ${CLUSTER_ANNOUNCE_PORT}',
      '--cluster-announce-bus-port ${CLUSTER_ANNOUNCE_BUS_PORT}'
    ]

  redis-cluster-3:
    image: redis
    restart: always
    container_name: redis-cluster-3
    ports:
      - 7002:6379
      - 17002:16379
    volumes:
      - ./data/7002:/data
    environment:
      - CLUSTER_ANNOUNCE_PORT=7002
      - CLUSTER_ANNOUNCE_BUS_PORT=17002
    command: [
      '--appendonly ${REDIS_APPENDONLY}',
      '--cluster-enabled ${REDIS_CLUSTER_ENABLED}',
      '--cluster-config-file ${REDIS_CLUSTER_CONFIG_FILE}',
      '--cluster-node-timeout ${REDIS_CLUSTER_NODE_TIMEOUT}',
      '--cluster-announce-ip ${HOST_IP}',
      '--cluster-announce-port ${CLUSTER_ANNOUNCE_PORT}',
      '--cluster-announce-bus-port ${CLUSTER_ANNOUNCE_BUS_PORT}'
    ]

  redis-cluster-4:
    image: redis
    restart: always
    container_name: redis-cluster-4
    ports:
      - 7003:6379
      - 17003:16379
    volumes:
      - ./data/7003:/data
    environment:
      - CLUSTER_ANNOUNCE_PORT=7003
      - CLUSTER_ANNOUNCE_BUS_PORT=17003
    command: [
      '--appendonly ${REDIS_APPENDONLY}',
      '--cluster-enabled ${REDIS_CLUSTER_ENABLED}',
      '--cluster-config-file ${REDIS_CLUSTER_CONFIG_FILE}',
      '--cluster-node-timeout ${REDIS_CLUSTER_NODE_TIMEOUT}',
      '--cluster-announce-ip ${HOST_IP}',
      '--cluster-announce-port ${CLUSTER_ANNOUNCE_PORT}',
      '--cluster-announce-bus-port ${CLUSTER_ANNOUNCE_BUS_PORT}'
    ]

  redis-cluster-5:
    image: redis
    restart: always
    container_name: redis-cluster-5
    ports:
      - 7004:6379
      - 17004:16379
    volumes:
      - ./data/7004:/data
    environment:
      - CLUSTER_ANNOUNCE_PORT=7004
      - CLUSTER_ANNOUNCE_BUS_PORT=17004
    command: [
      '--appendonly ${REDIS_APPENDONLY}',
      '--cluster-enabled ${REDIS_CLUSTER_ENABLED}',
      '--cluster-config-file ${REDIS_CLUSTER_CONFIG_FILE}',
      '--cluster-node-timeout ${REDIS_CLUSTER_NODE_TIMEOUT}',
      '--cluster-announce-ip ${HOST_IP}',
      '--cluster-announce-port ${CLUSTER_ANNOUNCE_PORT}',
      '--cluster-announce-bus-port ${CLUSTER_ANNOUNCE_BUS_PORT}'
    ]

  redis-cluster-6:
    image: redis
    restart: always
    container_name: redis-cluster-6
    ports:
      - 7005:6379
      - 17005:16379
    volumes:
      - ./data/7005:/data
    environment:
      - CLUSTER_ANNOUNCE_PORT=7005
      - CLUSTER_ANNOUNCE_BUS_PORT=7005
    command: [
      '--appendonly ${REDIS_APPENDONLY}',
      '--cluster-enabled ${REDIS_CLUSTER_ENABLED}',
      '--cluster-config-file ${REDIS_CLUSTER_CONFIG_FILE}',
      '--cluster-node-timeout ${REDIS_CLUSTER_NODE_TIMEOUT}',
      '--cluster-announce-ip ${HOST_IP}',
      '--cluster-announce-port ${CLUSTER_ANNOUNCE_PORT}',
      '--cluster-announce-bus-port ${CLUSTER_ANNOUNCE_BUS_PORT}'
    ]